from __future__ import annotations

import numpy as np
import pandas as pd

from income_analyzer import (
    _fmp_series,
    _is_fmp_statement,
    _safe_ratio,
    _years_from_statement,
    extraer_dato_robusto,
)


def _is_fmp_cashflow(df: pd.DataFrame | None) -> bool:
    if df is None or df.empty:
        return False
    known_columns = {
        "operatingCashFlow", "capitalExpenditure", "freeCashFlow",
        "commonStockRepurchased", "dividendsPaid",
    }
    return bool(known_columns & set(df.columns))


def analizar_flujo_efectivo(
    cf_df: pd.DataFrame | None,
    is_df: pd.DataFrame | None,
) -> dict[str, pd.DataFrame | str] | None:
    """Analiza flujos de caja usando columnas FMP normalizadas."""
    if cf_df is None or cf_df.empty or is_df is None or is_df.empty:
        return None

    if not _is_fmp_cashflow(cf_df):
        return _analizar_flujo_efectivo_legacy(cf_df, is_df)

    years = _years_from_statement(cf_df)
    if not years:
        return None

    capex = _fmp_series(cf_df, ["capitalExpenditure", "investmentsInPropertyPlantAndEquipment"], years, default=0.0)
    recompras = _fmp_series(cf_df, ["commonStockRepurchased", "repurchasesOfStock"], years, default=0.0)
    fco = _fmp_series(cf_df, ["operatingCashFlow", "netCashProvidedByOperatingActivities"], years, default=np.nan)
    dividendos = _fmp_series(cf_df, ["dividendsPaid", "commonDividendsPaid"], years, default=0.0)
    depreciacion = _fmp_series(cf_df, ["depreciationAndAmortization"], years, default=np.nan).abs()

    if _is_fmp_statement(is_df):
        beneficio_neto = _fmp_series(is_df, ["netIncome"], years)
    else:
        cols_is = sorted([c for c in is_df.columns if str(c).isdigit() and len(str(c)) == 4])
        beneficio_neto = extraer_dato_robusto(
            is_df,
            ["NetIncomeLoss", "NetIncomeLossAvailableToCommonStockholdersBasic", "ProfitLoss", "Net income", "Net earnings"],
            cols_is,
        ).reindex(years)

    fcf_reportado = _fmp_series(cf_df, ["freeCashFlow"], years, default=np.nan)
    fcf_calculado = fco + capex.fillna(0.0)
    fcf = fcf_reportado.fillna(fcf_calculado)
    capex_abs = capex.abs()

    df_cf_ratios = pd.DataFrame(index=years)
    df_cf_ratios["CAPEX % sobre Beneficio"] = _safe_ratio(capex_abs, beneficio_neto, multiplier=100).fillna(0)
    df_cf_ratios["Recompras (B USD)"] = recompras.abs() / 1e9
    df_cf_ratios["Free Cash Flow (B USD)"] = fcf / 1e9
    df_cf_ratios["CFO (B USD)"] = fco / 1e9
    df_cf_ratios["CAPEX (B USD)"] = capex_abs / 1e9
    df_cf_ratios["Dividendos (B USD)"] = dividendos.abs() / 1e9

    capex_mantenimiento = pd.concat([depreciacion, capex_abs], axis=1).min(axis=1)
    df_cf_ratios["Owner Earnings (B USD)"] = (fco - capex_mantenimiento) / 1e9

    media_capex = df_cf_ratios["CAPEX % sobre Beneficio"].replace([np.inf, -np.inf], np.nan).mean()
    if pd.isna(media_capex) or media_capex == 0:
        status = "Sin datos de CAPEX suficientes"
    elif media_capex < 25:
        status = "Ventaja Duradera (CAPEX < 25%)"
    elif media_capex < 50:
        status = "Empresa Saludable (CAPEX 25-50%)"
    else:
        status = "Alta Intensidad de Capital (CAPEX > 50%)"

    return {"ratios": df_cf_ratios.replace([np.inf, -np.inf], np.nan).round(2), "veredicto": status}


def _analizar_flujo_efectivo_legacy(
    cf_df: pd.DataFrame,
    is_df: pd.DataFrame,
) -> dict[str, pd.DataFrame | str] | None:
    cols_cf = sorted([c for c in cf_df.columns if str(c).isdigit() and len(str(c)) == 4])
    cols_is = sorted([c for c in is_df.columns if str(c).isdigit() and len(str(c)) == 4])
    if not cols_cf:
        return None

    capex = extraer_dato_robusto(
        cf_df,
        ["PaymentsToAcquirePropertyPlantAndEquipment", "PaymentsToAcquireProductiveAssets", "Capital expenditures", "Additions to property"],
        cols_cf,
    )
    recompras = extraer_dato_robusto(
        cf_df,
        ["PaymentsForRepurchaseOfCommonStock", "PaymentsForRepurchaseOfEquity", "Repurchases of common stock"],
        cols_cf,
    )
    fco = extraer_dato_robusto(
        cf_df,
        ["NetCashProvidedByOperatingActivities", "Cash generated by operating activities", "Net cash provided by operating activities"],
        cols_cf,
    )
    beneficio_neto = extraer_dato_robusto(
        is_df,
        ["NetIncomeLoss", "NetIncomeLossAvailableToCommonStockholdersBasic", "ProfitLoss", "Net income", "Net earnings"],
        cols_is,
    ).reindex(cols_cf)
    dividendos = extraer_dato_robusto(
        cf_df,
        ["PaymentsOfDividendsCommonStock", "PaymentsOfDividends", "DividendsPaid", "Cash dividends paid"],
        cols_cf,
    )
    depreciacion = extraer_dato_robusto(
        cf_df,
        ["DepreciationDepletionAndAmortization", "DepreciationAndAmortization", "Depreciation", "Amortization"],
        cols_cf,
    ).abs()

    capex_abs = capex.abs()
    df_cf_ratios = pd.DataFrame(index=cols_cf)
    df_cf_ratios["CAPEX % sobre Beneficio"] = _safe_ratio(capex_abs, beneficio_neto, multiplier=100).fillna(0)
    df_cf_ratios["Recompras (B USD)"] = recompras.abs() / 1e9
    df_cf_ratios["Free Cash Flow (B USD)"] = (fco - capex_abs) / 1e9
    df_cf_ratios["CFO (B USD)"] = fco / 1e9
    df_cf_ratios["CAPEX (B USD)"] = capex_abs / 1e9
    df_cf_ratios["Dividendos (B USD)"] = dividendos.abs() / 1e9
    capex_mantenimiento = pd.concat([depreciacion, capex_abs], axis=1).min(axis=1)
    df_cf_ratios["Owner Earnings (B USD)"] = (fco - capex_mantenimiento) / 1e9

    media_capex = df_cf_ratios["CAPEX % sobre Beneficio"].replace([np.inf, -np.inf], np.nan).mean()
    if pd.isna(media_capex) or media_capex == 0:
        status = "Sin datos de CAPEX suficientes"
    elif media_capex < 25:
        status = "Ventaja Duradera (CAPEX < 25%)"
    elif media_capex < 50:
        status = "Empresa Saludable (CAPEX 25-50%)"
    else:
        status = "Alta Intensidad de Capital (CAPEX > 50%)"

    return {"ratios": df_cf_ratios.replace([np.inf, -np.inf], np.nan).round(2), "veredicto": status}
